language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajay/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajay/docker-react-test npm test

after_success:
  - docker build -t ajaysoni101/multi-client ./client
  - docker build -t ajaysoni101/multi-nginx ./nginx
  - docker build -t ajaysoni101/multi-server ./server
  - docker build -t ajaysoni101/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub

  - docker push ajaysoni101/multi-client
  - docker push ajaysoni101/multi-nginx
  - docker push ajaysoni101/multi-server
  - docker push ajaysoni101/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-480321802861"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY